-- MySQL Script generated by MySQL Workbench
-- Wed Mar 28 18:25:21 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USER` (
  `ssn` INT(9) NOT NULL,
  `userType` INT NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `sex` CHAR(1) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`ssn`),
  UNIQUE INDEX `ssn_UNIQUE` (`ssn` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PATIENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PATIENT` (
  `ssn` INT(9) NOT NULL,
  `physicianID` INT(9) NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `sex` CHAR(1) NOT NULL,
  `DOB` DATE NOT NULL,
  `insurance` VARCHAR(45) NULL,
  `address` VARCHAR(100) NULL,
  `email` VARCHAR(45) NULL,
  `notes` VARCHAR(300) NULL,
  PRIMARY KEY (`ssn`),
  UNIQUE INDEX `ssn_UNIQUE` (`ssn` ASC),
  CONSTRAINT `physicianID`
    FOREIGN KEY (`ssn`)
    REFERENCES `mydb`.`USER` (`ssn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MODALITY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MODALITY` (
  `modID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `cost` DOUBLE NOT NULL,
  `minutes` INT NOT NULL,
  PRIMARY KEY (`modID`),
  UNIQUE INDEX `modID_UNIQUE` (`modID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`APPOINTMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`APPOINTMENT` (
  `appID` INT NOT NULL AUTO_INCREMENT,
  `physicianID` INT(9) NOT NULL,
  `patientID` INT(9) NOT NULL,
  `dateTime` DATETIME NOT NULL,
  `totalCost` DOUBLE NULL,
  `modality1` INT NULL,
  PRIMARY KEY (`appID`),
  UNIQUE INDEX `appID_UNIQUE` (`appID` ASC),
  INDEX `physicianID_idx` (`physicianID` ASC),
  INDEX `patientID_idx` (`patientID` ASC),
  INDEX `mod1_idx` (`modality1` ASC),
  CONSTRAINT `physicianID`
    FOREIGN KEY (`physicianID`)
    REFERENCES `mydb`.`USER` (`ssn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `patientID`
    FOREIGN KEY (`patientID`)
    REFERENCES `mydb`.`PATIENT` (`ssn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `mod1`
    FOREIGN KEY (`modality1`)
    REFERENCES `mydb`.`MODALITY` (`modID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PACS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PACS` (
  `imageID` INT NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(100) NOT NULL,
  `transcript` VARCHAR(300) NULL,
  `apppintmentID` INT NULL,
  PRIMARY KEY (`imageID`),
  UNIQUE INDEX `imageID_UNIQUE` (`imageID` ASC),
  UNIQUE INDEX `image_UNIQUE` (`image` ASC),
  INDEX `appID_idx` (`apppintmentID` ASC),
  CONSTRAINT `appID`
    FOREIGN KEY (`apppintmentID`)
    REFERENCES `mydb`.`APPOINTMENT` (`appID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ORDER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ORDER` (
  `orderID` INT NOT NULL AUTO_INCREMENT,
  `physicianSSN` INT(9) NOT NULL,
  `patientSSN` INT(9) NOT NULL,
  PRIMARY KEY (`orderID`),
  UNIQUE INDEX `orderID_UNIQUE` (`orderID` ASC),
  INDEX `patientSSN_idx` (`patientSSN` ASC),
  INDEX `physicianSSN_idx` (`physicianSSN` ASC),
  CONSTRAINT `physicianSSN`
    FOREIGN KEY (`physicianSSN`)
    REFERENCES `mydb`.`USER` (`ssn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `patientSSN`
    FOREIGN KEY (`patientSSN`)
    REFERENCES `mydb`.`PATIENT` (`ssn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
